stages:
    - test
    - benchmark

test:
    stage: test
    script: 
        - cd deliverable
        - ./test.sh
    tags:
        - "fdedi"

benchmark:
    stage: benchmark
    script: 
        - cd deliverable
        - ./build.sh
        - cd ..
        - /data/delivery/measureTaxi ./deliverable/submit.sh
    tags:
        - "fdedi"